version: '3.8'
services:
  postgres:
    image: nateai/challenge-ios-db:1.2.0
    restart: always
    environment:
      POSTGRES_USER: nate 
      POSTGRES_PASSWORD: access
      POSTGRES_DB: product
    build:
      dockerfile: Dockerfile.db
      context: .
    ports:
      - 6543:5432

  seed:
    image: nateai/challenge-ios-seed:1.2.0
    environment:
      DATABASE_URL: postgres://nate:access@postgres:5432/product
    build:
      dockerfile: Dockerfile.seed
      context: .
    depends_on:
      - postgres

  api:
    image: nateai/challenge-ios-api:1.2.0
    environment:
      DATABASE_URL: postgres://nate:access@postgres:5432/product
    build:
      dockerfile: Dockerfile.api
      context: .
    ports:
      - 3000:3000
      - 4000:4000
    depends_on:
      - postgres
      - seed
