# version: "3.8"
# services:
#   postgres:
#     container_name: "challenge-database"
#     image: postgres
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_USER: nate
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: challenge
#       PGDATA: /data

#   # What does this container do?
#   # database-build:
#   #   container_name: "challenge-database-build"
#   #   image: nateai/challenge-ios-database:1.0.0
#   #   build:
#   #     dockerfile: Dockerfile.database.build
#   #     context: .
#   #     args:
#   #       DATABASE_URL: postgres://nate:password@postgres:5432/challenge?schema=public
#   #   environment:
#   #     DATABASE_URL: postgres://nate:password@postgres:5432/challenge?schema=public
#   #   depends_on:
#   #     - postgres

#   backend:
#     container_name: "challenge-backend"
#     image: nateai/challenge-ios-apis:1.0.0
#     build:
#       dockerfile: Dockerfile
#       context: .
#       args:
#         DATABASE_URL: postgres://nate:password@postgres:5432/challenge?schema=public
#     ports:
#       - "3000:3000"
#       - "4000:4000"
#     environment:
#       DATABASE_URL: postgres://nate:password@postgres:5432/challenge?schema=public
#     depends_on:
#       - postgres
#       - database-build
